services:
  - type: web
    name: document-upload-api
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn document_upload:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: STORAGE_PATH
        value: /data/user_data
      - key: OPENAI_API_KEY
        sync: false # This will prompt you to enter the value during deployment
      - key: PYTHONUNBUFFERED
        value: "true"
    disk:
      name: user-data
      mountPath: /data
      sizeGB: 10

  - type: web
    name: agent-manager
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn agent_manager:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: STORAGE_PATH
        value: /data/user_data
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: LIVEKIT_URL
        sync: false
      - key: LIVEKIT_API_KEY
        sync: false
      - key: LIVEKIT_API_SECRET
        sync: false
      - key: SIP_TRUNK_ID
        sync: false
    disk:
      name: user-data
      mountPath: /data
      sizeGB: 10 